# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "newuser@gmail.com",
  "login": "New_User",
  "firstname": "Mr",
  "lastname": "Smith",
  "password": "BlaBlaBlaPass"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/6434021b03ea2143d2db41f2 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "newuser@gmail.com",
  "password": "BlaBlaBlaPass"
}

###

# Change user password
PATCH http://localhost:3000/api/auth/6434021b03ea2143d2db41f2/password HTTP/1.1
Content-Type: application/json

{
  "oldPassword": "newPassword123",
  "newPassword": "BlaBlaBlaPass"
}

###
